# Generated by Django 3.1.3 on 2021-02-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botsummit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('phone_number', models.PositiveIntegerField()),
                ('desired_sub', models.CharField(choices=[('BScCSIT', 'BScCSIT'), ('BIT', 'BIT')], max_length=25)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
